folio-org/mgr-applications

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, src/main/resources/swagger.api/am.yaml
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
=> FOLIO-3678 FOLIO-3937 Use GitHub Workflows api-lint and api-schema-lint and api-doc

pom.xml
Upgrade folio-libraries version for: `folio-security`, `folio-backend-testing`
- Upgrade folio-libraries version for: `folio-security`, `folio-backend-testing`
- 
environment. Communication is paramount if that is to be …
=> MGRTENANT-8 Upgrade folio-libraries version

pom.xml, src/main/java/org/folio/am/domain/entity/InterfaceReferenceEntity.java
The official version of Spring for Quesnelia is 3.2 (see https://wiki.folio.org/display/TC/Quesnelia).
- Upgrade Spring Boot parent version and affected libraries, plugins
environment. Communication is paramount if that is …
=> MODROLESKC-21 Upgrade Spring Boot to v3.2.1

.github/CODEOWNERS, .gitignore, PERSONAL_DATA_DISCLOSURE.md, pom.xml
Maven deploy works not properly. It should be fixed.
- fix pom file
- add required files
inter-team dependencies …
=> FIX: maven deploy issue

src/test/java/org/folio/am/support/extensions/impl/PostgresContainerExtension.java
User postgres alpine version for test containers to decrease image size
inter-team dependencies increase.
While …
=> User postgres alpine version for test containers

README.md, pom.xml, src/main/java/org/folio/am/controller/ApplicationController.java, src/main/java/org/folio/am/controller/ApplicationDiscoveryController.java, src/main/java/org/folio/am/controller/BaseController.java, src/main/java/org/folio/am/controller/ModuleBootstrapController.java, src/main/java/org/folio/am/controller/ModuleDiscoveryController.java, src/main/resources/application.yml, src/test/java/org/folio/am/controller/ApplicationControllerTest.java, src/test/java/org/folio/am/controller/ModuleBootstrapControllerTest.java, src/test/java/org/folio/am/controller/ModuleDiscoveryControllerTest.java, src/test/java/org/folio/am/it/RoutePrefixIT.java, src/test/java/org/folio/am/support/extensions/impl/KongGatewayExtension.java
Add router path prefix to the generated by OpenAPI generator endpoints
- Implement single dependency variable for all libraries provided in `applications-poc-tools`
- Add router path prefix as env variable
environment. …
=> MGRAPPS-8 Implement router prefix for the generated endpoints

NEWS.md, pom.xml
Release v1.1.0
- Add NEWS.md
inter-team dependencies increase.
While it's helpful for reviewers to help identify …
=> MGRAPPS-9 Release v1.1.0

docker/Dockerfile.fips, docker/config/java.security.fips, pom.xml, src/main/java/org/folio/am/ApplicationManagerApplication.java
Create a docker file for the mgr-applications module that is based on the FIPS-140-2 compliant base image (ubi9/openjdk-17-runtime)
US: [MGRAPPS-12](https://folio-org.atlassian.net/browse/MGRAPPS-12)
* create a separate `Dockerfile.fips` in the modules repo with FIPS-140-2 compliance
* customize java security settings (see `java.security.fips`)
* remove dependency to BC libs from pom file and the code. The libs are downloaded during docker image build
- Do Rally stories exist to …
=> MGRAPPS-12 Create a docker file for the mgr-applications module that is based on the FIPS-140-2 compliant base image (ubi9/openjdk-17-runtime)

Jenkinsfile
Automatic Docker image build implementation
https://jenkins-aws.indexdata.com/job/folio-org/job/mgr-applications/job/RANCHER-1502/8/console
environment. Communication is paramount if that is to be achieved, especially as the …
=> Rancher 1502

src/test/java/org/folio/am/support/extensions/impl/KongGatewayExtension.java
Upgrade kong version to 3.7.1
inter-team dependencies increase.
While it's helpful for reviewers to help …
=> KONG-10: upgrade kong version to 3.7.1

pom.xml, src/test/java/org/folio/am/it/ApplicationIT.java, src/test/java/org/folio/am/support/TestValues.java
Applies new ModuleDescriptor model from `applications-poc-tools` and validates it
- Validate that new ModuleDescriptor model is properly saved
environment. Communication is paramount if that is to be achieved, especially as …
=> MGRAPPS-23 Validate extensions field in ModuleDescriptor

Jenkinsfile
enable docker build in Jenkinsfile
=> enable docker build in Jenkinsfile

src/test/java/org/folio/am/it/ApplicationIT.java, src/test/java/org/folio/am/support/TestValues.java
After some discussion, we agreed to leverage the existing "metadata" field rather than introduce a new “extensions” field. 
[MGRAPPS-29](https://folio-org.atlassian.net/browse/MGRAPPS-29)
Revert the changes from MGRAPPS-23 related to adding an “extensions” field.
Ideally, all the PRs involved in breaking changes would be merged on the same …
=> MGRAPPS-29: Revert MGRAPPS-23

pom.xml
=> Release 1.3.3

pom.xml
Upgrade applications-poc-tools to 1.5.7
=> Upgrade applications-poc-tools to 1.5.7

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/MGRAPPS-32
=> Release v1.4.0

pom.xml
Increases keycloak-admin-client to v25.0.6
- Increases keycloak-admin-client to v25.0.6
- Use the latest snapshot versions of `applications-poc-tools` library components
environment. Communication is paramount if that is to …
=> KEYCLOAK-24 Increase version of keycloak-admin-client to v25.0.6

src/main/java/org/folio/am/integration/kong/KongDiscoveryListener.java
Added logging to verify if Kong Routes Management is enabled and properly called.
inter-team dependencies …
=> MGRAPPS-35: Added logging to Kong Discovery Listener.

src/main/java/org/folio/am/repository/ModuleBootstrapViewRepository.java, src/main/java/org/folio/am/service/ModuleBootstrapService.java, src/main/java/org/folio/am/utils/ModuleIdUtils.java, src/test/java/org/folio/am/repository/ModuleBootstrapViewRepositoryIT.java, src/test/java/org/folio/am/service/ModuleBootstrapServiceTest.java, src/test/java/org/folio/am/support/TestConstants.java, src/test/java/org/folio/am/utils/ModuleIdUtilsTest.java, src/test/resources/sql/application-descriptor-with-routes.sql, src/test/resources/sql/module-interface-references.sql
https://folio-org.atlassian.net/browse/MGRAPPS-45
Fix issue with multiple versions of same module being returned as dependencies in module bootstrap information.
environment. Communication is paramount if that is to be …
=> MGRAPPS-45

pom.xml, src/main/java/org/folio/am/service/ModuleBootstrapService.java, src/main/resources/swagger.api/schemas/module/bootstrap/moduleBootstrapDiscovery.json, src/main/resources/swagger.api/schemas/module/bootstrap/permissionModel.json, src/test/java/org/folio/am/service/ModuleBootstrapServiceTest.java
https://folio-org.atlassian.net/browse/MGRAPPS-44
Return module permissions in module bootstrap info
inter-team …
=> MGRAPPS-44: Return module permissions in module bootstrap info

pom.xml, src/main/java/org/folio/am/integration/kong/KongDiscoveryListener.java, src/test/java/org/folio/am/integration/kong/KongDiscoveryListenerTest.java
https://folio-org.atlassian.net/browse/MGRENTITLE-92
Cleanup deprecated Kong route management logic with tenant-specific routes
environment. Communication is paramount if that is to be achieved, especially as the number of …
=> MGRENTITLE-92: remove tenant-specific routes logic

Dockerfile, Jenkinsfile, docker/Dockerfile.fips, pom.xml
MGRAPPS-46: Upgrade to Java 21.
inter-team dependencies increase.
While it's helpful for reviewers to help …
=> MGRAPPS-46: Upgrade to Java 21.

NEWS.md, pom.xml, src/main/java/org/folio/am/integration/messaging/outbox/event/OutboxUpdatedEvent.java, src/main/java/org/folio/am/service/ApplicationInterfaceValidatorService.java, src/main/resources/descriptors/ModuleDescriptor.json, src/main/resources/swagger.api/schemas/dependency.json, src/test/java/org/folio/am/it/KongRegistrationIT.java, src/test/java/org/folio/am/mapper/ApplicationDescriptorMapperTest.java, src/test/java/org/folio/am/service/ApplicationInterfaceValidatorServiceTest.java
[MGRAPPS-57](https://folio-org.atlassian.net/browse/MGRAPPS-57)
Introduce the notion of optional dependencies at the application level
- Updated Dependency schema with a new field "optional"
- Remove optional dependencies from the validations
- Added tests
---
=> MGRAPPS-57: Introduce optional application dependencies

README.md, src/main/resources/application.yml
Since testing the routemanagement feature was done, we can now enable the feature by default.
- ROUTEMANAGEMENT_ENABLE=true
---
=> enable routemanagement by default

checkstyle/checkstyle-checker.properties, checkstyle/checkstyle-suppressions.xml, pom.xml, src/main/java/org/folio/am/service/ApplicationDescriptorsValidationService.java, src/main/java/org/folio/am/service/DependenciesValidator.java, src/main/java/org/folio/am/service/ModuleDiscoveryService.java, src/main/java/org/folio/am/utils/CollectionUtils.java
Add method length checkstyle rule and refactor code for compliance
---
=> feat(checkstyle): add method length checkstyle rule and refactor code for compliance
